name: Generate Issues Webpage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'

    - name: Cache CPAN Modules
      uses: actions/cache@v3
      with:
        path: ~/.cpanm
        key: cpanm-${{ runner.os }}-${{ hashFiles('cpanfile.snapshot') }}
        restore-keys: |
          cpanm-${{ runner.os }}-

    - name: Install Dependencies
      run: cpanm --notest --installdeps .

    - name: Run Perl script
      run: ./issue.pl html > ./issue/index.html

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install npm dependencies
      run: npm install
      working-directory: browser

    - name: Run npm build
      run: npm run build
      working-directory: browser

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./issue
